### ISSUE TITLE
Invalid URL in plugin.json

### ISSUE THREAD

**Issue by cschol** [jimallman/interrobang-rack-modules#1]
```
https://ibang.com
```

does not load. Is this URL valid?

**Comment by jimallman** [comment]
I own this domain, but my website has been down for some time. I can use my GitHub homepage instead, or stand up a simple placeholder site (which I've been meaning to do anyway). Do you have a preference?

**Comment by cschol** [comment]
Github homepage is fine for now until your site is up. Thanks!

**Comment by jimallman** [comment]
I've put up a simple homepage at the existing URL https://ibang.com. Please take another look when you have a moment.

**Comment by jimallman** [comment]
@cschol I'm going to close this, since the new homepage is up and running. Hope that's not a break of protocol.

**Comment by cschol** [comment]
All good. Thank you.
