### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by cschol** [jimallman/interrobang-rack-modules#3]
```
[Interrobang] Building plugin on platform win...src/ScribbleStrip.cpp:95:8: error: ‘function’ in namespace ‘std’ does not name a template type
   std::function<void(std::string)> changeHandler;
        ^~~~~~~~
src/ScribbleStrip.cpp: In member function ‘virtual void ScribbleStripWidget::EventParamField::onSelectKey(const rack::event::SelectKey&)’:
src/ScribbleStrip.cpp:107:9: error: ‘changeHandler’ was not declared in this scope
     if (changeHandler) {
         ^~~~~~~~~~~~~
src/ScribbleStrip.cpp:107:9: note: suggested alternative: ‘ThreadHandle’
     if (changeHandler) {
         ^~~~~~~~~~~~~
         ThreadHandle
src/ScribbleStrip.cpp: In member function ‘virtual void ScribbleStripWidget::appendContextMenu(rack::ui::Menu*)’:
src/ScribbleStrip.cpp:133:14: error: ‘struct ScribbleStripWidget::EventParamField’ has no member named ‘changeHandler’
   editField->changeHandler = [=](std::string text) {
              ^~~~~~~~~~~~~
make: *** [build/src/ScribbleStrip.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
FAILED

x86_64-w64-mingw32-g++  -std=c++11 -Wsuggest-override   -fPIC -I/home/cschol/src/Rack-SDK/Rack-SDK/include -I/home/cschol/src/Rack-SDK/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/plugin.cpp.o src/plugin.cpp
x86_64-w64-mingw32-g++  -std=c++11 -Wsuggest-override   -fPIC -I/home/cschol/src/Rack-SDK/Rack-SDK/include -I/home/cschol/src/Rack-SDK/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/ScribbleStrip.cpp.o src/ScribbleStrip.cpp
/home/cschol/src/Rack-SDK/Rack-SDK/compile.mk:68: recipe for target 'build/src/ScribbleStrip.cpp.o' failed

>>> BUILD FAILURES:
Interrobang win
```

**Comment by jimallman** [comment]
Odd, I thought this was fixed in commit 3b4b537. Are you using the latest master branch?

Would it help if I try to set up the Azure cross-platform compilation pipeline [as described here](https://community.vcvrack.com/t/azure-pipelines-for-github-allows-build-of-plugin/2651/2)? That would give me a heads-up to problems on other platforms, so I can at least try a fix before wasting your time...

**Comment by SteveRussell33** [comment]
I can confirm this was fixed in https://github.com/jimallman/interrobang-rack-modules/commit/3b4b53786576d763d8f3978dc1c7bac93d966bc1 as detailed here https://github.com/jimallman/interrobang-rack-modules/issues/2#issuecomment-609073554 as this is the same build error I had.

**Comment by cschol** [comment]
@jimallman You told me to use 853e4ec in the update request.

**Comment by jimallman** [comment]
I see. I'm still learning the VCV plugin dance. :bowtie:

So I should bump the version and commit hash for even minor changes. Got it! Going to do that now...

**Comment by cschol** [comment]
Unless the plugin has been released there is no need to update the **plugin version**, but I need to know which SHA to integrate, so you need to let me know which one it is if there are changes made. I will not just grab the `HEAD`.

**Comment by jimallman** [comment]
That makes sense; thanks for clarifying.

> Unless the plugin has been released there is no need to update the plugin version

Version 1.0.0 somehow [made its way into the library](https://library.vcvrack.com/?query=&brand=Interrobang), so I guess the latest could be v1.0.1 or v1.0.2. Is it OK to skip patch versions in the next release?

One more question: How can I tell a plugin version has been released, short of checking the online plugin library? Does it happen automatically whenever [my plugin's issue](https://github.com/VCVRack/library/issues/639#event-3185492868) is closed?

**Comment by SteveRussell33** [comment]
@jimallman I check the library repo commits https://github.com/VCVRack/library/commits/v1 if you see that Andrew has updated the manifest for your plugin, then it's been released to the library. 

I've starred this repo (and any others I'm interested in) and have bookmarked the "Your stars" link from the account icon top right of any GitHub page, filtered for updates: https://github.com/SteveRussell33?direction=desc&sort=updated&tab=stars visiting this page will show you when the Library has been updated and so you can check what manifests have been updated, thus seeing what new plugin versions have been added to the library and when this was done.

HTH

**Comment by cschol** [comment]
@jimallman I integrate plugin releases into the `library` repository. Then Andrew's build will pick them up with the next build update and they will be released in the Plugin Manager.

Skipping a version is not a problem. The issue on Github will be reopened when a new version is available. It will be closed when the plugin has been released in the Plugin Manager.
